// Code generated by "stringer -type=blockTyp"; DO NOT EDIT.

package parser

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[blockQuote-0]
}

const _blockTyp_name = "blockQuote"

var _blockTyp_index = [...]uint8{0, 10}

func (i blockTyp) String() string {
	if i >= blockTyp(len(_blockTyp_index)-1) {
		return "blockTyp(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _blockTyp_name[_blockTyp_index[i]:_blockTyp_index[i+1]]
}
