// Code generated by "stringer -type=linkVariant"; DO NOT EDIT.

package parser

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[onePartLink-0]
	_ = x[twoPartLink-1]
}

const _linkVariant_name = "onePartLinktwoPartLink"

var _linkVariant_index = [...]uint8{0, 11, 22}

func (i linkVariant) String() string {
	if i >= linkVariant(len(_linkVariant_index)-1) {
		return "linkVariant(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _linkVariant_name[_linkVariant_index[i]:_linkVariant_index[i+1]]
}
