// Code generated by "stringer -type=Category"; DO NOT EDIT.

package node

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CategoryError-0]
	_ = x[CategoryBlock-1]
	_ = x[CategoryInline-2]
}

const _Category_name = "CategoryErrorCategoryBlockCategoryInline"

var _Category_index = [...]uint8{0, 13, 26, 40}

func (i Category) String() string {
	if i < 0 || i >= Category(len(_Category_index)-1) {
		return "Category(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Category_name[_Category_index[i]:_Category_index[i+1]]
}
