// Code generated by "stringer -type=ListType"; DO NOT EDIT.

package node

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnorderedList-0]
	_ = x[NumberedList-1]
}

const _ListType_name = "UnorderedListNumberedList"

var _ListType_index = [...]uint8{0, 13, 25}

func (i ListType) String() string {
	if i < 0 || i >= ListType(len(_ListType_index)-1) {
		return "ListType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ListType_name[_ListType_index[i]:_ListType_index[i+1]]
}
