// Code generated by "stringer -type=PrinterMode"; DO NOT EDIT.

package node

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PrintData-1]
	_ = x[PrintOffsets-2]
	_ = x[PrintLocation-4]
}

const (
	_PrinterMode_name_0 = "PrintDataPrintOffsets"
	_PrinterMode_name_1 = "PrintLocation"
)

var (
	_PrinterMode_index_0 = [...]uint8{0, 9, 21}
)

func (i PrinterMode) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _PrinterMode_name_0[_PrinterMode_index_0[i]:_PrinterMode_index_0[i+1]]
	case i == 4:
		return _PrinterMode_name_1
	default:
		return "PrinterMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
