// Code generated by "stringer -type=PrinterMode"; DO NOT EDIT.

package node

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PrintAll-6]
	_ = x[PrintData-2]
	_ = x[PrintLocation-4]
}

const (
	_PrinterMode_name_0 = "PrintData"
	_PrinterMode_name_1 = "PrintLocation"
	_PrinterMode_name_2 = "PrintAll"
)

func (i PrinterMode) String() string {
	switch {
	case i == 2:
		return _PrinterMode_name_0
	case i == 4:
		return _PrinterMode_name_1
	case i == 6:
		return _PrinterMode_name_2
	default:
		return "PrinterMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
