// Code generated by "stringer -type=Type"; DO NOT EDIT.

package node

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeLine-0]
	_ = x[TypeVerbatimLine-1]
	_ = x[TypeWalled-2]
	_ = x[TypeHanging-3]
	_ = x[TypeRankedHanging-4]
	_ = x[TypeFenced-5]
	_ = x[TypeText-6]
	_ = x[TypeUniform-7]
	_ = x[TypeEscaped-8]
}

const _Type_name = "TypeLineTypeVerbatimLineTypeWalledTypeHangingTypeRankedHangingTypeFencedTypeTextTypeUniformTypeEscaped"

var _Type_index = [...]uint8{0, 8, 24, 34, 45, 62, 72, 80, 91, 102}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
