// Code generated by "stringer -type=Token"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EOF-0]
	_ = x[LINEFEED-1]
	_ = x[INDENT-2]
	_ = x[COMMENT-3]
	_ = x[VLINE-4]
	_ = x[GT-5]
	_ = x[HYPEN-6]
	_ = x[GRAVEACCENTS-7]
	_ = x[LOWLINES-8]
	_ = x[GAP-9]
	_ = x[PAG-10]
	_ = x[LTP-11]
	_ = x[PTL-12]
	_ = x[DPUNCT-13]
	_ = x[TEXT-14]
}

const _Token_name = "EOFLINEFEEDINDENTCOMMENTVLINEGTHYPENGRAVEACCENTSLOWLINESGAPPAGLTPPTLDPUNCTTEXT"

var _Token_index = [...]uint8{0, 3, 11, 17, 24, 29, 31, 36, 48, 56, 59, 62, 65, 68, 74, 78}

func (i Token) String() string {
	if i >= Token(len(_Token_index)-1) {
		return "Token(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Token_name[_Token_index[i]:_Token_index[i+1]]
}
