// Code generated by "stringer -type=Token"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EOF-0]
	_ = x[LINEFEED-1]
	_ = x[INDENT-2]
	_ = x[COMMENT-3]
	_ = x[VLINE-4]
	_ = x[GT-5]
	_ = x[HYPEN-6]
	_ = x[TEXT-7]
}

const _Token_name = "EOFLINEFEEDINDENTCOMMENTVLINEGTHYPENTEXT"

var _Token_index = [...]uint8{0, 3, 11, 17, 24, 29, 31, 36, 40}

func (i Token) String() string {
	if i >= Token(len(_Token_index)-1) {
		return "Token(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Token_name[_Token_index[i]:_Token_index[i+1]]
}
